NCOLS = 10
NROWS = 20
NHIDDEN_ROWS = 2
NTOTAL_ROWS = NROWS + NHIDDEN_ROWS
CELL_SIZE = 30
MARGIN = 20 

VISIBLE_BOARD_WIDTH = NCOLS * CELL_SIZE
VISIBLE_BOARD_HEIGHT = NROWS * CELL_SIZE

NUM_PREVIEW = 5
PREVIEW_WIDTH = 5 * CELL_SIZE
PREVIEW_HEIGHT = (NUM_PREVIEW * 3 + 1) * CELL_SIZE

HOLD_WIDTH = 5 * CELL_SIZE
HOLD_WIDTH = HOLD_WIDTH

STAT_WIDTH = VISIBLE_BOARD_WIDTH
STAT_HEIGHT = 4 * CELL_SIZE

WINDOW_WIDTH = MARGIN + HOLD_WIDTH + MARGIN + VISIBLE_BOARD_WIDTH + MARGIN + PREVIEW_WIDTH + MARGIN 
WINDOW_HEIGHT = MARGIN + VISIBLE_BOARD_HEIGHT + STAT_HEIGHT + MARGIN

GRAY = (128,128,128)
BORDER_GRAY = (60, 60, 60)


DAS = 10
ARR = 1
FRAMES_TIL_FALL = 60
FRAMES_TIL_LOCK = 120
SOFTDROP_FRAMES = 2

SPAWN_COORDINATE_X = NCOLS // 2 - 2
SPAWN_COORDINATE_Y = NTOTAL_ROWS - NHIDDEN_ROWS - 1